class Error(Exception):
    pass


class MyIOError(Error):
    pass
